docs/getting-started.md, docs/tutorials.md
This will add a "Getting Started" page with initial setup instructions and explanations on what the hello world example does.
=> Add getting started documentation page

public/index.html
I tried to improve the text content and added links to other tools that are mentioned in the text.
=> Reviewed website content

config.toml
=> Link to correct github content for editing

content/docs/grammar-language.md
* Added documentation for fragment rules
* Added documentation for guarded rules
=> Added fragment rules and guarded rules

content/docs/configuration-services.md, content/docs/getting-started.md, content/docs/grammar-language.md, content/docs/tutorials.md
Closes https://github.com/langium/langium-website/issues/27
=> Introduce page weights

content/docs/configuration-services.md, content/docs/grammar-language.md
I did another review round over the new configuration chapter and applied my changes here.
=> Reworked new configuration chapter

content/docs/grammar-language.md
Given that https://github.com/langium/langium/pull/422 has been merged, we should update the documentation on guard conditions.
=> Update documentation on guard conditions

content/docs/ast-types.md, content/docs/configuration-services.md, content/docs/grammar-language.md
I would not go too much into details in the grammar chapter, though, because this should be explained in full depth in the upcoming chapter on type inference.
=> Added a few explanations about returns vs. infers

content/docs/getting-started.md
Includes minor changes from 0.3 which have to be reflected in the documentation.
=> Update getting started guide to 0.3

content/docs/document-lifecycle.md
Are the new explanations understandable?
=> Added more details to document lifecycle

.gitpod.yml, package.json
Forked a command `npm start` for GitPod to `npm run start:gitpod`.
Cleaned up package.json
=> Fixing the build scripts for Hugo

hugo/content/docs/_index.md, hugo/content/docs/getting-started.md, hugo/content/docs/langium-overview.md
Lists the key features of Langium. Serves as a birds eye view on what Langium has to offer to potential downstream developers. I'm open to suggestion on how to expand/improve certain sections.
=> Overview of Langium

hugo/static/custom.css
target the svg element using class name and added margin left space
=> extra space added to svg heart icon

hugo/content/docs/document-lifecycle.md
See langium/langium#622 - this has to be reflected in the documentation.
=> Updated documentation about scope computation

hugo/static/custom.css
Closes https://github.com/langium/langium-website/issues/98
=> Fix graph edge colors

README.md, hugo/layouts/partials/langium-footer.html, hugo/layouts/partials/langium-header.html, hugo/layouts/playground/baseof.html
* using a [grid](https://play.tailwindcss.com/iynmIDdW0m) layout
* NOT using [flex-box](https://play.tailwindcss.com/4js449QH1r) because I want the neighbor cells having same measures
=> Make playground's layout more responsive

hugo/content/guides/builtin-library.md
Closes https://github.com/langium/langium-website/issues/68
=> Add guide for builtin libraries

hugo/content/docs/grammar-language.md, hugo/content/docs/langium-overview.md, hugo/content/guides/scoping/_index.md, hugo/content/guides/scoping/class-member.md, hugo/content/guides/scoping/qualified-name.md, hugo/content/showcase/_index.html, hugo/static/custom.css
Closes https://github.com/langium/langium-website/issues/58
=> Add guides for scoping

hugo/content/guides/formatting.md
Explains how an adopter would customize their own formatter for their language.
=> Add formatting guide

hugo/content/_index.html, hugo/layouts/partials/langium-header.html
Adds a `Try it` and `Getting Started` button to the homepage. Also makes the header sticky (on desktop).
=> Add buttons to homepage

hugo/assets/scripts/statemachine/statemachine.tsx
Fixed the issue mentioned in this issue:
https://github.com/langium/langium-website/issues/165
=> Fixed not updating state

hugo/content/docs/getting-started.md
Hello :wave:
I updated a path in **Getting Started** based off of my experience generating a project following the instructions in the paragraphs above
=> fix(getting-started): file path

.github/workflows/deploy.yml, .github/workflows/preview.yml, netlify.toml
See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3578
=> Removed Netlify config and added GH actions

hugo/assets/scripts/arithmetics/arithmetics.tsx, hugo/assets/scripts/domainmodel/domainmodel.tsx, hugo/assets/scripts/minilogo/minilogo.tsx, hugo/assets/scripts/sql/ui.tsx, hugo/assets/scripts/statemachine/statemachine.tsx
Fixes the showcases in the GitHub preview environment
=> Fix relative path for web workers

hugo/content/api/_index.md, hugo/layouts/partials/langium-mobile-menu.html, hugo/layouts/partials/langium-nav.html
=> Link the API docs

hugo/content/docs/reference/semantic-model.md
Closes https://github.com/eclipse-langium/langium-website/pull/259
=> Fix incorrect type in semantic model docs
