eclipse-langium/langium-website

src/style.css, static/css/style.css
This fixes a deviation of the carousel rendering between Chrome and Safari.
Before it looked on large screens like this (left: Chrome, right: Safari):
After applying this fix, it looks correct:
This fix does not change rendering on small screens. Before and after look like this:
=> Fixes cropped carousel items in Safari

content/docs/grammar-language.md
Here is a first draft to the grammar language section of the Langium documentation.
Open for any suggestion about the content, structure, etc.
Most likely some parts need to be reworked to be in line with v0.3
=> Grammar documentation

content/docs/getting-started.md, content/docs/grammar-language.md
* Moved EBNF syntax for terminal rules and "Terminal Fragments" to the end.
* Moved declaration and entry rule description to the beginning of the "Parser Rules" section.
* Moved "Cardinalities" from terminal rules to parser rules EBNF syntax.
* Added "Groups" and "Alternatives" to parser rules EBNF syntax (similar to terminal rules).
* Moved three larger examples to the end of the "Parser Rules" section ("More Examples").
* Added more explanation to "Tree-Rewriting Actions".
=> Reordered and extended grammar documentation

content/docs/configuration-services.md
First draft for the documentation about configuration of services via dependency injection.
It has two main parts:
1. Adding new services
2. Extending/Overriding existing services
The last part is a brief description of all default services and their dependencies.
=> Added draft dependency injection

static/custom.css
Resolves #24
Changed the margins on headings and paragraphs to look less monotonous.
It works by overriding CSS rules from the hugo theme via `static/custom.css`. The modified classes are at the bottom of `static/custom.css`.
=> Changed margins on headings

hugo/layouts/partials/langium-footer.html, hugo/layouts/partials/langium-header.html
This addresses some issues that are visible on the current site regarding the footer and showcase page, these are:
- footer elements are not centered
- footer does not compress well for mobile view
- header & footer font is overriden by monaco for the showcase page
The following gif shows these issues:
And this one demonstrates these issues fixed in this PR.
=> Fix Footer Issues & Missing Font for Showcase

hugo/content/playground/_index.html, hugo/content/playground/common.ts, hugo/content/playground/data.ts, hugo/content/playground/langium-worker.ts, hugo/content/playground/monarch-generator.ts, hugo/content/playground/share-link.ts, hugo/content/playground/user-worker.ts, hugo/layouts/langium/baseof.html, hugo/layouts/partials/langium-footer.html, hugo/layouts/partials/langium-head.html, hugo/layouts/partials/langium-header.html, hugo/layouts/partials/langium-nav.html, hugo/layouts/playground/baseof.html, hugo/package.json, hugo/static/custom.css, package-lock.json
Closes https://github.com/langium/langium-website/issues/89
Adds a button to the playground that puts a playground URL with compressed grammar and content into the clipboard. Any user who opens that URL will be presented with the original grammar and content.
=> Add share feature to playground

hugo/content/docs/ast-types.md
Adds an extra paragraph that lets users know that declared types are:
- bleeding edge
- still being developed
- can help with grammar design
- generally well-suited for mature/complex languages
This should be helpful to guide new developers on their choice of using declared types, and also to keep a close eye on their semantic model when doing so.
Open to suggestions on wording and such.
=> Extra Paragraph about Declared Types

hugo/content/playground/_index.html, hugo/content/showcase/statemachine.html, hugo/package.json, package-lock.json
codicon.ttf is now directly contained in the css encoded as base64 data url. Therefore only one helper function is needed and the path error in the console is gone.
=> Updated monaco-editor-wrapper 1.3.2 Removing codicon.ttf loading error

hugo/content/docs/grammar-language.md
Related to an issue opened on Langium, https://github.com/langium/langium/issues/681. Negated tokens don't work in Langium the same way that they do in Xtext. We may address this, but for the sake of transparency, I've updated the docs to make this incompatibility clear.
If we rectify this at a later time, we can update the docs to reflect this.
=> Adds Details about Negated Tokens in EBNF

hugo/content/docs/grammar-language.md, hugo/content/docs/sematic-model.md
The current documentation explains fairly well how to refactor dummy rules, but doesn't really explain why they are sometimes needed in the first place.
This change addresses this, as it proposes a use case, where we first introduce a problem, which can be solved by using a dummy rule. Afterwards, we refactor our solution using declared types to remove the dummy rule again.
=> Improve dummy rule documentation

hugo/assets/scripts/statemachine.tsx, hugo/package.json, package-lock.json, package.json, tailwind/package.json
Because the main changes were already merged by Emil, this PR only adds the `package.json` clean-up and that the latest version of `@typefox/monaco-editor-react/bundle` directly exposes `monaco`
I only declared `devDependencies` everywhere now, because all deps are only needed to create an output and therefore this seemed reasonable.
=> Sort package json content

hugo/content/docs/getting-started.md, hugo/content/docs/grammar-language.md, hugo/content/docs/langium-overview.md, hugo/content/docs/sematic-model.md, hugo/content/tutorials/validation.md
The antlr syntax highlighting is fairly close to Langium. We could also add some special syntax highlighting for Langium later, but this is a quick win improve readability of Langium code snippets.
=> Use antlr syntax highlighting for langium code

hugo/assets/scripts/statemachine.tsx
Updates the Statemachine react code to include a rough approach for de-serializing a Langium-based AST. In addition, this also includes some examples of how that AST can then be traversed to retrieve specific information, which could then drive the generation of UI elements as desired.
=> Adds AST Deserializer + Example Usage

hugo/content/tutorials/langium_and_monaco.md
fix shell command separation in npm build configuration snippet ("npx shx ...")
=> fix documentation in langium_and_monaco.md

hugo/content/guides/builtin-library.md
It took me a little bit to realize that the `FileSystemProvider` is added to the client not the server.
=> Reword builtin-library.md a little bit.

hugo/content/docs/getting-started.md
Since the glossary doesn't exist the sentence about looking into it should not be shown
=> Sentence about glossary commented out.

hugo/config.toml, hugo/content/docs/sematic-model.md, hugo/static/prism/langium-prism.js, hugo/static/prism/prism.css
Previously:
New:
Colors are taken from the light/dark default vscode themes.
=> Improve syntax highlight for light theme

hugo/static/index.js
Click back/forward buttons on the carousel had a runtime error saying `loop` is undefined.
=> fix carousel back/forward buttons not working

hugo/content/docs/configuration-services.md
The documentation on customizing your language editor with additional services in docs/configuration-services.md was lacking a section on how to resolve cyclic dependencies. Langium will throw an error in case of such cyclic dependencies that links to a non-existing documentation page. Once this PR is merged and published, the error message in Langium may be updated to refer to this new section: https://langium.org/docs/configuration-services/#resolving-cyclic-dependencies
=> Documentation on resolving cyclic dependencies

hugo/content/showcase/arithmetics.html
Just changed the description from
to
=> Hotfix: Changed the arithmetics description

hugo/content/guides/code-bundling.md
With newer versions of esbuild, the build/watch API has changed quite a bit. This change updates our documentation to reflect that.
=> Update esbuild config for new versions

hugo/content/guides/builtin-library.md
While following the guide for builtin libraries, I noticed a few places for potential improvements:
- Most importantly: add a type definition for `HelloWorldSharedServices`, because such a type is not generated by yeoman but required for the definition of `HelloWorldSharedModule`.
- Determine the file size via `Buffer.from(...).length`, so the actual byte size of the string is given.
- Add a call `super.loadAdditionalDocuments(folders, collector)`, for the case that the super class defines some additional behavior we might want to keep (though currently not the case).
Let me know what you think about these changes.
=> Minor fixes for the builtin library guide

hugo/content/playground/common.ts
Closes #163 , where the second program editor instance would crash due to not getting a correct grammar from the previous editor. In such a case there was no program editor to dispose of for future grammars, which would block the program editor from being setup again from that point forward. This just catches errors during the editor disposal process (such as trying to dispose a non-running editor), reports them, and unblocks subsequent setup of a new program editor.
Quick gif of the result below.
=> Handle Failed Editor Disposal

hugo/content/docs/configuration-services.md, hugo/content/guides/builtin-library.md, hugo/content/tutorials/generation.md, hugo/content/tutorials/generation_in_the_web.md, hugo/content/tutorials/langium_and_monaco.md, hugo/content/tutorials/validation.md, hugo/content/tutorials/writing_a_grammar.md
After v1.2.0 (specifically https://github.com/eclipse-langium/langium/pull/954), the yeoman generator for new Langium projects has a slightly different directory structure. This just updates references to the old path, `src/language-server/`, with just `src/language/`.
=> Replace old references to "language-server" directory with "language".

hugo/content/tutorials/generation_in_the_web.md, hugo/content/tutorials/langium_and_monaco.md
This updates the last couple of tutorials for *Langium + Monaco* & *Generation in the Web* to use more recent versions of Langium (2.0.2) and the [MEW](https://www.npmjs.com/package/monaco-editor-wrapper) (3.1.0). This follows the recent changes to langium-minilogo to version 2.0.0, which serves as the basis for a good chunk of these tutorials as well.
It would be great to get suggestions for wording and general flow improvements; as well as any typos that snuck in.
As a side note, I've noticed code-blocks are not overflowing as expected (instead of scrolling along the horizontal, they simply overflow past the right-hand boundary). This is not ideal, and appears to be a CSS issue, but is unrelated to the changes here.
=> Update Langium + Monaco Tutorials

hugo/content/playground/common.ts
This addresses an issue with the recent playground changes, where a failed wrapper start was not disposing of the wrapper afterwards. This led to some strange behavior when working with grammars that would produce an invalid LS.
The solution here removes a previous workaround, and instead disposes of the wrapper in the appropriate place.
There is still a remaining issue with worker teardown, which does not succeed when the LC is stuck in a 'starting' state (see https://github.com/TypeFox/monaco-components/issues/41). We're able to address this by first terminating the worker manually, then disposing the wrapper.
Note that the wrapper dispose will fail when the LC is stuck, but the teardown up to that point is sufficient to clean up the rest of the artifacts (editor & associated elements).
=> Dispose of Wrapper on Failed Start

.github/workflows/preview.yml, hugo/config.toml, hugo/content/playground/common.ts
As requested in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4075.
Additional changes that needed to be made for previews to be correctly displayed:
- use relative links when generating the site
- update playground to load additional js files relatively instead of absolutely
=> Support publishing of PR previews to the langium-previews repo

.github/workflows/preview.yml
Need to unpin the action as it checks out itself using the provided tag
=> Unpin the pr-preview-action

.github/workflows/preview.yml
This fixes #213 .
After the fixes to the action have been merged and included in a release, we can finally pin the dependency.
=> Update pr-preview-action and pin it

.github/workflows/preview.yml
This should fix job failures like https://github.com/eclipse-langium/langium-website/actions/runs/7274912030
=> Added pull-request: write permission to remove-preview job

hugo/content/tutorials/building_an_extension/index.md
This page does not currently work out of the box when applied to the project that comes out of `generator-langium` because the location of the extension entry point was moved from `src/extension.ts` to `src/extension/main.ts`. This changes the documentation to match the [current default location](https://github.com/eclipse-langium/langium/blob/main/packages/generator-langium/templates/vscode/src/extension/main.ts).
=> Fix default path to extension entry point

hugo/content/docs/sematic-model.md
Declared types are now a stable feature.
=> Remove "bleeding edge" notice

hugo/content/docs/recipes/scoping/class-member.md
Improves readability of the class member scoping invocation graph by making clear which answer belongs to which request.
=> Specify class member scoping order

hugo/content/playground/user-validator.ts, hugo/content/playground/user-worker.ts
Addresses and closes #226 
For the moment I am using warnings instead of errors for failed linking.
This PR is in draft mode, so I will change the implementation along the discussion inside of the issue.
=> Playground: Customize linking errors

hugo/content/docs/recipes/scoping/_index.md, hugo/content/docs/recipes/scoping/file-based.md
I added a recipe based on the Hello World example about file-based imports. They are added shortly to the scoping overview page.
I used the "Simpsons" for exporting persons, feel free to suggest some cooler persons.
One might add hints for missing validations or other LSP services, that make this feature more attractive.
Closes #234
=> Recipe: File-based symbol import/export

hugo/content/docs/recipes/builtin-library.md
LangiumDocumentFactory was missing and LangiumSharedServices has moved to langium/lsp
=> Update imports to match latest

hugo/content/docs/learn/workflow/_index.md
This PR addresses #256. 
The rendering issues might be caused by markdown numbered list recognition in flow chart nodes (e.g. `1. Install Yeoman`).
Escaping the `.` as proposed [here](https://stackoverflow.com/a/50916345), i.e. `1\. Install Yeoman`, did not work for me (Safari 17.6):
As a workaround this PR adds a non-breaking space to prevent numbered lists, e.g. `1.&nbsp;Install Yeoman`.
This seems to fix the rendering issue (tested on Safari 17.6):
Additionally, the flow chart node `for each additional\ngrammar change` seems to not render the line break as intended.
Replacing `\n` with `<br/>` results in a proper line break (Safari 17.6):
=> #256 Fix rendering issue in "Langium's workflow" flowchart

hugo/content/docs/recipes/builtin-library.md
If you close VS Code with a builtin library file open, it won't be reinstated the next time you start VS Code again. Instead, it will display an error, saying that there's no file system provider for the respective URI scheme available. This change adds additional info on how to instruct VS Code to load the file correctly when encountering the URI scheme.
=> Add activation event for builtin library

hugo/content/docs/learn/minilogo/customizing_cli.md, hugo/content/docs/learn/minilogo/generation.md
The CLI section and generate of the minilogo tutorial reference a file 'src/cli/index.ts' which does not exist. Updated the path to 'src/cli/main.ts' instead. Make the path explicit, even when it is mentioned the second time, to avoid possible confusion with other 'main.ts' files.
=> Fix filepath to main.ts in customizing_cli.md

hugo/content/docs/recipes/formatting.md
The import statement in the example code was not working.
I changed it from
```
import { AbstractFormatter, AstNode, Formatting } from 'langium';
```
to
```
import { AstNode } from 'langium';
import { AbstractFormatter, Formatting } from 'langium/lsp';
```
=> formatting.md: Fix imports
